### ISSUE TITLE
Models and Tables

### ISSUE THREAD

**Issue by oobbles** [oobbles/06-23-fania#13]
What tables will your application need? _albums, styles, artists, albums_styles, albums_artists_
What are the schemas (names and types of columns) for each table? _See below_
What are the relationships between your application's data entities? _See below_
Which columns in your tables are foreign keys? _album_id, style_id and artist_id in the lookup tables_

<img src="http://i.imgur.com/kXbHAjc.jpg">

<img src="http://i.imgur.com/W1RlPAL.png">

**Comment by sumeetjain** [comment]
In "albums" (for example), "artists" would not be a column (at least not how we're doing things for this project). It'll be a method in your `Artist` class instead, which fetches the artists based on a given album's set of "artist_id" values from the bridge table.

Also table names need to be lower cased to meet the naming rules.

**Comment by oobbles** [comment]
The "set" things are from joining them.  See hand drawn table and text above.  Everything should be syntactically correct. (I did underscore album_id, etc.)
